function apply_kuramoto_style(fig)
%APPLY_KURAMOTO_STYLE Shared visual style for report figures.
if nargin < 1
    fig = gcf;
end
set(fig, 'Color', 'w');
set(findall(fig, 'Type', 'axes'), ...
    'FontName', 'Arial', ...
    'FontSize', 8.5, ...
    'LineWidth', 1.1, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'XColor', [0.05 0.05 0.05], ...
    'YColor', [0.05 0.05 0.05]);
set(findall(fig, 'Type', 'text'), ...
    'FontName', 'Arial', ...
    'FontWeight', 'normal', ...
    'Color', [0.05 0.05 0.05]);
set(findall(fig, 'Type', 'legend'), ...
    'FontName', 'Arial', ...
    'Box', 'off', ...
    'Color', 'w', ...
    'TextColor', [0.05 0.05 0.05]);
end
